### PR TITLE
Separate debug channel ability added

### PR DESCRIPTION
**Pull request by omarrodriguez15**

### CODE REVIEW

**Comment by ImDevinC** [comment]
Checkout my comment in #4 about those variables. That needs to be fixed before this comes in.  

As for this change, this already exists. If you set a DEBUG_WEBHOOK, the debug messages get sent to that webhook (IE: a separate channel). Can you elaborate on why this is needed?

**Comment by omarrodriguez15** [comment]
I could see how this may not be useful for everyone, but for me it is useful because I am in a workspace were I have to request new webhooks through our slack admins. So instead of requesting a new webhook I just have one webhook I use for all my bots and override the channels they use.

**Comment by ImDevinC** [comment]
Thanks for the clarification. Once the base PR your code is taken from is fixed, then I can take this into the master branch. But the breaking changes from the base PR are holding this up for the moment.

**Comment by omarrodriguez15** [comment]
This PR includes changes from #4 PR and merged in the latest changes from master.

**Comment by ImDevinC** [comment]
Thanks! Looks good on my end and doesn't break existing instances. Of note, I don't have this setup on my machine so I'm trusting your changes work. 👍

**Comment by omarrodriguez15** [comment]
Tested with and without the debug channel property. As well as with debug on and off. Should work...or as the saying goes "it works on my machine"😏

**Comment by omarrodriguez15** [comment]
@stardust20 If you are configuring your web hooks through the Slack API leave both the CHANNEL and DEBUG_CHANNEL property blank.

**Comment by stardust20** [comment]
Thanks @omarrodriguez15 , I'll try that.

**Pull request merged**
