### PR TITLE
Adding ability to customize slack messaging using private.py

### PR DESCRIPTION
**Pull request by omarrodriguez15**
Added username, avatar, and slack channel for bot to use when sending messages.

### CODE REVIEW

**Comment by omarrodriguez15** [comment]
I can add some additional instructions in the main readme if needed.

**Comment by josueboix** [comment]
You can customise these settings so easily from https://api.slack.com when you setup the app, and add a nice World Cup logo picture instead of an emoji.

**Comment by omarrodriguez15** [comment]
Problem for me is I am not an admin in my slack workspace and I have to submit request for new webhooks. So instead of creating a webhook for each bot I just reuse the same one and customize it's name and avatar on the bots side.

**Comment by stardust20** [comment]
I haven't thought of that actually since I have access to my workspace. This is actually a handy add to the bot indeed.

**Comment by omarrodriguez15** [comment]
Also might be nice to have the debug info go to a separate "debug channel". I could add that change but don't if I should go ahead and lump it in with this PR or make a separate one.

**Comment by stardust20** [comment]
I opened an issue related to the debug mode, and I agree, it should be another one.

**Comment by ImDevinC** [comment]
This is a semi-breaking change as it requires users to have those variables defined in their private.py file already and if they don't the script will crash. I've gotten a lot of messages from users who aren't very adept at programming, so this should probably check for the existence of these variables before checking their value.

**Comment by omarrodriguez15** [comment]
Understood. I am normally a .net developer so I am not familiar with the whole loading a file through the import statement worked. I assumed it was like javascript and would just evaluate as undefined or none.

**Pull request merged**
